### ISSUE TITLE
`collectstatic` brings in all js testing utilities in series-0.4

### ISSUE THREAD

**Issue by keithschulze** [mytardis/mytardis#1121]
Running `./mytardis.py collectstatic` now pulls in a large number of unnecessary js utilities (e.g., testing). Would be good to avoid these if possible because they are not required in the static assets.

**Comment by wettenhj** [comment]
Hi @keithschulze, it's presumably not `collectstatic` that does this, but the `npm install` run before `collectstatic`.  Depending on your `npm` version, you can run `npm install --production` or `npm install --only=production` to avoid the `devDependencies` in package.json.

**Comment by wettenhj** [comment]
As discussed in person, running the full ```npm install``` is recommended in a local development environment, so you can run the JS tests.  We should probably add ```NPM_FILE_PATTERNS``` to ```tardis/default_settings/static_files.py```, so that ```collectstatic``` doesn't copy unnecessary folders from within ```node_modules/```.  See: https://github.com/kevin1024/django-npm/blob/master/README.md

**Comment by wettenhj** [comment]
Fixed in https://github.com/mytardis/mytardis/pull/1125
