### ISSUE TITLE
notify_migration_status task has User object as argument which is not easily serializable

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#1420]
The default serialization in Celery 4 has changed from Pickle to JSON, and attempting to run the openid_migration app's notify_migration_status task with a User object as an argument gives an error:

```EncodeError: <User: testuser1> is not JSON serializable```

Replacing the User argument with a user_id argument would avoid this problem.

https://github.com/mytardis/mytardis/blob/develop/tardis/apps/openid_migration/tasks.py#L16

@manishkumr

**Comment by wettenhj** [comment]
Also email_user_task:

https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/tasks.py#L73

**Comment by jameswettenhall** [comment]
Fixed here: https://github.com/mytardis/mytardis/pull/1423
