### ISSUE TITLE
Standardise archive output format to BagIt

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#153]
Implementing the BagIt specification wouldn't take particularly long, and would allow generated archives to be read in by compatible software:
http://en.wikipedia.org/wiki/BagIt

[original LH ticket](http://mytardis.lighthouseapp.com/projects/90227/tickets/143)

 This ticket has 0 attachment(s).

**Comment by grischa** [comment]
Hasn't come up for a while... closing
