### ISSUE TITLE
Dataset_file with blank filename

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#155]
Suggestion: when new Dataset_file is created, check that the filename is non-blank. Otherwise, you get a file with a name like "var/store/1/2", which breaks messily.

[original LH ticket](http://mytardis.lighthouseapp.com/projects/90227/tickets/147)

 This ticket has 0 attachment(s).

**Comment by grischa** [comment]
I believe this does not apply anymore. Filename is required on DataFile, but the actual file is written via DataFileObjects.
Can you remember how this issue came up, @steveandroulakis ?
