### ISSUE TITLE
Error on ldap login when LDAP_USER_LOGIN_ATTR = "cn"

### ISSUE THREAD

**Issue by rbur004** [mytardis/mytardis#1664]
Request Method:    POST
Request URL:          http://130.216.218.66/login/
Exception Type:      KeyError
Exception Value:     'uid'
Exception Location: /home/mytardis/mytardis/tardis/tardis_portal/auth/ldap_auth.py in authenticate, line 163

In ldap_auth.py, the values of xxx are hardcoded, rather than using LDAP_USER_ATTR_MAP.

i.e. 'uid', 'giventName', 'sn' and 'mail' are hardcoded.
lines 163 on in ldap_auth.py
            if ldap_result[0][1]['uid'][0] == username.encode():
                # check if the given username in combination with the LDAP
                # auth method is already in the UserAuthentication table
                user = ldap_result[0][1]
                return {'first_name': user['givenName'][0],
                        'last_name': user['sn'][0],
                        "id": user['uid'][0],
                        "email": user['mail'][0]}

My defs change 'uid' to 'cn' and the resulting entries from the debug dump show them as the following:

LDAP_USER_ATTR_MAP: {'cn': 'id', 'givenName': 'first_name', 'mail': 'email', 'sn': 'last_name'}
LDAP_USER_BASE:  'OU=People, dc=UoA, dc=auckland, dc=ac, dc=nz'
LDAP_USER_LOGIN_ATTR:  'cn'

**Comment by jameswettenhall** [comment]
Thanks for raising this @rbur004, it certainly looks like a bug.

Would you like to submit a pull request to fix it?

Otherwise, we can add it to our backlog.

**Comment by rbur004** [comment]
I'll leave it to you. I can read python, but haven't written more than a hello world.

**Comment by rbur004** [comment]
Also hardcodes 'uid' in  def getUsernameByEmail()

**Comment by jameswettenhall** [comment]
Hi @rbur004, I've submitted a pull request which I believe fixes this issue: https://github.com/mytardis/mytardis/pull/1680

Let me know what you need to be able to test out the fix yourself.  Can you test it from the pull request branch?  Or do you need us to tag a new MyTardis release?

**Comment by rbur004** [comment]
I have been installing from the master branch so far, but can spin up a VM and test this branch works. Will have a look at it tomorrow.

I did a quick hack to make the master branch work, by doing a search and replace of 'uid' with 'cn'. That got it working.  Onto the next road block :) , S3.

**Comment by jameswettenhall** [comment]
Glad you got it working by doing the search and replace.

If it's too much work to test a different branch, you could just test the updated `tardis/tardis_portal/auth/ldap_auth.py` from the PR branch (https://github.com/mytardis/mytardis/blob/3be93359e81ba236645f9a8298212a07c5cbbd78/tardis/tardis_portal/auth/ldap_auth.py) as a patch on the master branch.  There are some other very minor changes since the last time the master branch was updated, but they are mostly just fixing forwards compatibility with Python 3.

**Comment by rbur004** [comment]
It works fine. 

Had to google iteritems.  I can read most python, but this falls in the arcane for me :)
```
return {tardis_key: user[ldap_key][0] for ldap_key, tardis_key
                        in six.iteritems(self._user_attr_map)}
```

If you are moving to Python3, then the google response did indicate that iteritems() wasn't in Python 3 though, being replaced with items().

**Comment by jameswettenhall** [comment]
Hi @rbur004, FYI "six" is a compatibility layer allowing us to write code which works in both Python 2 and Python 3.  `six.iteritems` uses `iteritems` on Python 2 and `items` on Python 3: https://pythonhosted.org/six/#six.iteritems

Looks like you edited your comment, so maybe you already know this 😄
