### ISSUE TITLE
Install Documentation

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#173]
Update install docs to be compatible with 3.0. Consider updating http://mytardis.readthedocs.org/en/latest/install.html as the default install doc.

[original LH ticket](http://mytardis.lighthouseapp.com/projects/90227/tickets/122)

 This ticket has 0 attachment(s).

**Comment by grischa** [comment]
Done in 4068bc16f35e968dfb5ab1333fa9fcd062eb9058
