### ISSUE TITLE
Haystack (Single Search) incompatible with Django 1.4

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#181]
The current MyTardis master breaks single search functionality due to the current Haystack being incompatible with Django 1.4.

Info:
cannot import name MAX_SHOW_ALL_ALLOWED

Exception Location:	/var/www/mytardis/mytardis/eggs/django_haystack-1.2.6-py2.7.egg/haystack/admin.py in <module>, line 2
Python Executable:	/var/www/mytardis/mytardis/bin/uwsgi

More information here:

http://stackoverflow.com/questions/9961235/haystack-incompatible-with-django-1-4

[original LH ticket](http://mytardis.lighthouseapp.com/projects/90227/tickets/101)

 This ticket has 0 attachment(s).

**Comment by grischa** [comment]
Search has been updated to Haystack 2.x
