### ISSUE TITLE
Use celery for checking and re-indexing search documents

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#185]
Now that we have celery set up, we may as well use it for re-indexing search stuff rather than the script+cronjob we're currently using.

[original LH ticket](http://mytardis.lighthouseapp.com/projects/90227/tickets/99)

 This ticket has 0 attachment(s).

**Comment by wettenhj** [comment]
Search functionality certainly needs some work, but this 2013 issue describing "the script+cronjob we're currently using" is no longer relevant.  Closing.
