### ISSUE TITLE
Not able to add a user to the group

### ISSUE THREAD

**Issue by manishkumr** [mytardis/mytardis#1853]
Adding a user to the group with a username that contains a special character return 404 error status.

This is because the regex `(?P<username>[\w\.]+)` in the URL below matches only alphanumeric character and underscore

https://github.com/mytardis/mytardis/blob/c02c499cbc4835aa678f862ca482861d28b3f6e4/tardis/urls/group.py#L21

**Comment by jameswettenhall** [comment]
At this stage, the only character missing from our regular expression which we are likely to come across in a username is '@' - we already allow alphanumeric characters, underscores and dots.  So adding '@' to the permitted characters should suffice.  We can also add '+' and '-', just in case any of our users have them in their email address.
