### ISSUE TITLE
Single Search Fails on '_' in ParameterNames

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#193]
For instance, in the creative commons schema there exists the name (machine name) 'license_name', which displays in the solr schema.xml as

<code>&lt;field name=&quot;experiment_creative_commons_license_license_name&quot; type=&quot;text&quot; indexed=&quot;true&quot; stored=&quot;true&quot; multiValued=&quot;false&quot; /&gt;
</code>

and returns this error on re-indexing:

<code>Unhandled exception in thread started by &lt;bound method Thread.__bootstrap of &lt;Thread(Thread-1, stopped daemon -1211913328)&gt;&gt;
</code>

Resulting in the index not being updated at all.

While currently not 'the norm', underscores in parameter names is technically not illegal. So I suggest they be handled correctly (probably, hopefully, just an extra 'if' statement before a string replace or some such).

As an aside, all parameter names with multiple words used to be underscored instead of camelCased because xml elements use underscores as standard practice and at the time we were mainly concerned with METS XML ingest to MyTardis. Somewhere in the mix they were changed, for whatever reason.

[original LH ticket](http://mytardis.lighthouseapp.com/projects/90227/tickets/84)

 This ticket has 0 attachment(s).

**Comment by wettenhj** [comment]
Solr search was replaced by elasticsearch in this commit from 6 Jan 2016, so this issue is no longer relevant.
