### ISSUE TITLE
Carousel issue with thumbnail error handling

### ISSUE THREAD

**Issue by jameswettenhall** [mytardis/mytardis#2247]
In `tardis/tardis_portal/templates/tardis_portal/view_dataset.html`, the `img` element for each carousel item:

```
                <img alt="Preview image for Datafile #{{ datafile.id }}"
                     src="{{ thumbnail }}"
                     style="display: block; margin-left: auto; margin-right: auto;"
                     onerror="$(this).parents('.item').remove()"/>
```
uses `onerror="$(this).parents('.item').remove()"`

This is intended to hide the carousel item if an error occurs when retrieving the image.  But it doesn't work because the correct CSS class is `carousel-item`, not `item`:

```
<div class="{{ forloop.first|yesno:'active ,' }}carousel-item" style="height: 100%">
```

![carousel-thumbnail-error-handling](https://user-images.githubusercontent.com/42697835/72228404-53aa7e80-35fa-11ea-8253-e3bd562bc914.png)

**Comment by manishkumr** [comment]
fixed by [#2249](https://github.com/mytardis/mytardis/pull/2249)
