### ISSUE TITLE
"Login" usability on touchscreens

### ISSUE THREAD

**Issue by stevage** [mytardis/mytardis#230]
When logging in on a tablet (landscape mode), the keyboard covers up the bottom half of the login screen. Two issues with this:

1. You can't see the actual login button (you need to scroll).
2. The login button you can see is the one in the top right, which takes you back to the login page...

**Comment by jasonrig** [comment]
![img_0197](https://cloud.githubusercontent.com/assets/6635497/6342487/c79537c8-bc2d-11e4-9061-bf22c4207b91.JPG)

iPad Air

**Comment by grischa** [comment]
closed as irrelevant for now. The new UI will be tested with more devices
