### ISSUE TITLE
ANZSRC app dies on startup if it cannot fetch the FoR codes

### ISSUE THREAD

**Issue by crawley** [mytardis/mytardis#266]
This probably counts as a "once in a blue moon" event, but it happened on my UAT ... and could conceivably turn into a "hard error"

A fetch of the front page crashed with a stacktrace that indicated a problem while import / initializing the 'anzsrc_codes' app.  It appears that it attempted to fetch the contents of "http://purl.org/asc/1297.0/2008/for/", and the result was an HTML page (maybe an error page), not the RDF that it was expecting.  Refreshing the page "cured" the problem, so my guess is that this was a temporary outage that happened at an unlucky (for us).

The point is that this temporary outage could have been long term or even permanent.  So I'm thinking that this app ought to have some fallback in case the (external) source of FoR codes cannot be contacted.

**Comment by grischa** [comment]
has been done
