### ISSUE TITLE
Unable to add public key

### ISSUE THREAD

**Issue by OKaluza** [mytardis/mytardis#2684]
This is using store.erc.monash.edu instance.

I am unable to add my public key for sftp access, an error flashes up very briefly in red after entering details and pressing "Add Key", it took me quite a few tries to try and read it but I eventually made out the familiar `TypeError: a bytes-like object is required, not 'str'` error that crops up a lot when converting working python2 code to python3.

Looking at https://github.com/mytardis/mytardis/blob/5fe42d99d4f052c29da6117ed89027a227296ba8/tardis/apps/sftp/forms.py

I would guess the modification would be something like changing line 37 from:
    `data['public_key'] = base64.b64encode(k.get_base64().)`
to
    `data['public_key'] = base64.b64encode(k.get_base64().encode("ascii"))`

I confirmed this using a little test script below, without above change it gets the above TypeError in python3 only, python2 works with either:

```
from paramiko import RSAKey
import base64

public_key = 'AAAAB3NzaC1yc2EAAAABJQAAAQB/nAmOjTmezNUDKYvEeIRf2YnwM9/uUG1d0BYsc8/tRtx+RGi7N2lUbp728MXGwdnL9od4cItzky/zVdLZE2cycOa18xBK9cOWmcKS0A8FYBxEQWJ/q9YVUgZbFKfYGaGQxsER+A0w/fX8ALuk78ktP31K69LcQgxIsl7rNzxsoOQKJ/CIxOGMMxczYTiEoLvQhapFQMs3FL96didKr/QbrfB1WT6s3838SEaXfgZvLef1YB2xmfhbT9OXFE3FXvh2UPBfN+ffE7iiayQf/2XR+8j4N4bW30DiPtOQLGUrH1y5X/rpNZNlWW2+jGIxqZtgWg7lTy3mXy5x836Sj/6L'

print(public_key)
k = RSAKey(data=base64.b64decode(public_key))

data1 = base64.b64encode(k.get_base64().encode("ascii"))
print(data1)

data2 = base64.b64encode(k.get_base64())
print(data2)
```
I'm happy to make a pull request with this change if it helps.

**Comment by dyakhnov** [comment]
Generate new SSH key until I fix this issue and deploy hotfix.

**Comment by dyakhnov** [comment]
#2708

**Comment by dyakhnov** [comment]
This issue has been fixed, closing.
