### ISSUE TITLE
Creation and modification timestamps

### ISSUE THREAD

**Issue by crawley** [mytardis/mytardis#275]
While developing code for incremental archive, I found that I needed to track when the various components of an experiment have changed.  I discoverd that:
- Experiment has creation and modification datetime fields that   are updated automatically.
- Dataset has no creation / modification datetime fields. 
- Dataset_File has creation and modification datetime fields.  However, they are NOT updated automatically, and they can be null.  Indeed, in the main MyTardis codebase, I couldn't see anything that sets these fields.
- Parameters / ParameterSets have no creation or modification datetime fields.

So what are the implications?
- We can't tell when Dataset_Files are added to or removed from a Dataset.
- We can't always tell whether Dataset_Files are new or have been modified. (It depends on whether some non-core code populates and updates these fields.)
- We can't tell when properties on Experiments / Datasets / Dataset_Files have been added, changed or removed.

My suggested long-term fix for this is as follows:
- Add creation and modification timestamps to Dataset, make them non-null, and update them whenever a Dataset_File is added or removed or the Dataset title is changed.
- Change the creation and modification timestamps on Dataset_File to auto_now_add / auto_now, and non-null.
- Add a non-null timestamp field to each of the ParameterSet classes that is updated whenever a property is added, modified or removed.

The catch is that some ingestion apps _already_ use the Dataset_File timestamp fields.  So any core changes to the way that those 2 fields are managed need to be thoroughly discussed ...

**Comment by grischa** [comment]
Now addressed in #760
