### ISSUE TITLE
Architecture documentation refers to (out of date) Google code repository

### ISSUE THREAD

**Issue by guillaumeprevost** [mytardis/mytardis#276]
The myTardis architecture documentation refers to the old Google code SVN repository in the last part called "Source Code":
http://mytardis.readthedocs.org/en/latest/architecture.html#source-code

For example, it mentions:
- "Google SVN"
- "See http://code.google.com/p/mytardis/wiki/DevelopmentCycle"
- "Google wiki"

While going through the documentation with experienced developers, they also raised the issue that some diagrams seem to be out of date as well. It may be good to have a look at it as well.

**Comment by grischa** [comment]
Removed all references to Google code in latest docs updates (d2c4045)
