### ISSUE TITLE
Remove Django SECRET_KEY

### ISSUE THREAD

**Issue by grischa** [mytardis/mytardis#281]
The key should not be set in the default settings.
It should be set in test_settings, so tests run and for production people need to create their own.

This can be accomplished with the django_extensions `generate_secret_key` command-line option to `bin/django`.

This would also need some documentation in the installation section.

Rationale: https://docs.djangoproject.com/en/dev/topics/http/sessions/#using-cookie-based-sessions

**Comment by steveandroulakis** [comment]
https://github.com/mytardis/mytardis/pull/394
