### ISSUE TITLE
Tries to retrieve hashed image from wrong location

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#297]
Preview images (with the older base64 -> hashed file format?) don't show, as the file looks in the wrong location on the volume.

This potentially affects backwards compatibility for anything with preview images (diffraction image / bioformats / JEOL filters, namely).

ERROR:

Traceback (most recent call last):

  File "/var/www/mytardis/eggs/Django-1.5.1-py2.6.egg/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/var/www/mytardis/tardis/tardis_portal/views.py", line 268, in load_datafile_image
    return load_image(request, parameter)

  File "/var/www/mytardis/eggs/Django-1.5.1-py2.6.egg/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)

  File "/var/www/mytardis/tardis/tardis_portal/views.py", line 238, in load_image
    wrapper = FileWrapper(file(file_path))

IOError: [Errno 2] No such file or directory: u'/var/www/mytardis/var/store/0a3baf71-c567-43eb-9979-453018c20746'

----

Explanation of above:

My FILE_STORE_PATH = '/mnt/lards/mytardis/store'

Instead it's looking in /var/www/mytardis/var/store/ which appears to be the settings_changeme.py location.

The database Location field is correct.. so I'm unsure where it's getting the incorrect store path value at this point.

----

This public URL will trigger the error above: http://vera183.its.monash.edu.au/display/DatafileImage/load/7300/

That particular file exists under the correct store location eg. /mnt/lards/mytardis/store/0a3baf71-c567-43eb-9979-453018c20746

**Comment by grischa** [comment]
The metadata store location is now defined in `settings.METADATA_STORE_PATH`, and is soon to be changed to a storage box.
We'll revisit if any of the filters break, but then that probably means the filters need to be fixed.
