### ISSUE TITLE
User registration broken (on activation link)

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#307]
Logged by Chris Hines from Monash eResearch:

I hadn't event begun playing with it, just tried to create an account and log in noramlly with chromium and I ended up on django debugging pages:

I assume the productiony mytardis is at https://mytardis.massive.org.au

DoesNotExist at /
UserProfile matching query does not exist. Lookup parameters were {'user__id__exact': 69}
Request Method:  GET
Request URL:    https://mytardis.massive.org.au/
Django Version: 1.5.1
Exception Type: DoesNotExist
Exception Value:  
UserProfile matching query does not exist. Lookup parameters were {'user__id__exact': 69}
Exception Location:  /opt/mytardis/releases/28d0c3e3957a97682ddc4f2736b9ce4be4a56c89/eggs/Django-1.5.1-py2.7.egg/django/db/models/query.py in get, line 389
Python Executable:  /opt/mytardis/releases/28d0c3e3957a97682ddc4f2736b9ce4be4a56c89/bin/uwsgi
Python Version: 2.7.3

**Comment by wettenhj** [comment]
Automatic UserProfile creation was addressed in this commit: https://github.com/mytardis/mytardis/commit/ecb84969a1342551b64592918da51616ad877e64

The MyTardis server reference in this issue no longer exists, and running it with DEBUG=True in settings.py was only a temporary thing.
