### ISSUE TITLE
Author List

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#319]
Putting emails into the author list with format John Smith (john.smith@university.edu) used to work but now does not. It removes the email address entirely.

Also the display on both the form and the experiment view show authors as John Smith , Jane Doe (a space before the comma on each entry).

**Comment by steveandroulakis** [comment]
This is incorrect, I believe. It was a URL that worked in that field, and never an email.

**Comment by grischa** [comment]
We have an email field now, so the URL field can stay true to its name

**Comment by grischa** [comment]
@ianedwardthomas is gonna have another look at it

**Comment by ianedwardthomas** [comment]
If I enter "Ian Thomas (foo@rmit.edu.au), Bob Smith (x@rmit.edu.au)"
I get no emails or urls stored in ExperimentAuthor and extra spaces in experiment title page:
"Ian Thomas , Bob Smith"
