### ISSUE TITLE
DATETIME ParameterName type doesn't work

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#326]
If you make your ParameterName model object a 'DATETIME', then you can't actually save a parameter (it seems).

**Comment by pansapiens** [comment]
Problem arises here: https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/parameters.py#L383
where _value_ is a (unicode) string but needs to be converted to a Python datetime. Will need a Django datepicker on the UI and a defined date format for the API.
