### ISSUE TITLE
email and username fields are too short

### ISSUE THREAD

**Issue by carlohamalainen** [mytardis/mytardis#362]
The length of the email field needs to be extended:

    create user: "aaaaa.bbbbbbbbbb@newcastle.edu.au"
    mysql-haskell-test: StatusCodeException (Status {statusCode = 500,
    statusMessage = "INTERNAL SERVER ERROR"}) [("Date","Fri, 21 Nov 2014
    04:51:26 GMT"),("Server","WSGIServer/0.1
    Python/2.7.6"),("Vary","Cookie"),("Content-Type","application/json"),("X-Response-Body-Start","{\n
    \"error_message\": \"value too long for type character varying(30)\\n\",

The username field is also set at ```max_length=50``` which might be better being a bit longer too.

**Comment by grischa** [comment]
The workaround will do for now then. Cheers
We'll revisit it when we redo the authentication stuff
