### ISSUE TITLE
Distinguish more clearly between verified and unverified files in Facility Overview

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#372]
The Facility Overview doesn't distinguish between verified and unverified datafiles, and for partially complete uploads to staging, it lists file sizes recorded in datafile records, not the partial file size in staging.  Highlighting unverified datafiles more clearly would help to mitigate the risk of a facility manager deleting a datafile from an instrument PC after assuming it has been completely uploaded because it is listed in the Facility Overview with its complete file size.

Disclaimer: I'm using the "Via staging location" upload method described here: https://mytardis.readthedocs.org/en/latest/api.html, which I know is not officially supported in the current devel branch.

**Comment by wettenhj** [comment]
Comment from an "instrument facility manager" user: "In fact in the facility view it might be useful to show unverified files in a different colour. For users, I think it would be better not to show them at all."

**Comment by grischa** [comment]
Fixed
