### ISSUE TITLE
Facility View - not sure if sort by instrument is working correctly

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#373]
I tried sorting by instrument in the facility view and I ended up seeing data for instrument "James Test Microscope" in "Test Facility" split into two.  See screenshot.

![capture1](https://cloud.githubusercontent.com/assets/2209245/5848740/0373dc3a-a230-11e4-8f89-f42311e4abd9.PNG)

**Comment by jasonrig** [comment]
When was the last time you pulled from facility_view_improvements from my fork? I think I have already done something about this, but if you could confirm that would be good.

**Comment by wettenhj** [comment]
Good point, you might remember that I did a cherry pick from your branch some time ago rather than pulling in everything, which led to some git conflict dramas.  I've done a pull from your facility_view_improvements branch now, which has resulted in more conflicts.  I'll let you know when I've resolved them.

**Comment by jasonrig** [comment]
Yeah, I remember a few things broke after the assumption that an experiment was owned by a single user no longer applied.
Sorry if my git is a bit nightmarish. Still learning to do things properly.

**Comment by wettenhj** [comment]
OK, I've pulled in all of your changes, resolved conflicts, run collectstatic, and now the sort order looks better - and if fact it looks exactly right in Firefox, but in Chrome, I'm still finding that the datasets within experiment "James Test Microscope 2014-12-18" are split into two, even though they are all from the same "James Test Microscope" instrument in "Test Facility".

![sortbyinstrumentproblem](https://cloud.githubusercontent.com/assets/2209245/5849217/a338a7ea-a236-11e4-81f7-fad18d3b7f9e.PNG)

**Comment by jasonrig** [comment]
That's a bit weird, especially since I develop in Chrome. Caching maybe?
Try disabling the cache in chrome's dev tools or wipe in settings.

**Comment by wettenhj** [comment]
Yes I have tried clearing my cache (and running Chrome in Incognito mode).  This is Chrome on Windows 8.

**Comment by jasonrig** [comment]
Commit 786dac4063aaaed1446ec241cd33f22cbe6f8137 should fix the sorting
problem, but please test.

**Comment by wettenhj** [comment]
Yes, that works for me, thanks!

I'll leave the issue open to give you a chance to submit a pull request to merge your changes into the develop branch.

**Comment by jasonrig** [comment]
This can be closed
