### ISSUE TITLE
Facility View - not sure if sort by user is working correctly for multiple owners

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#374]
I'm attaching a before screenshot (before sorting by user) and an after screenshot (after sorting by user).  Is there a problem with some experiments having multiple owners?

In the "before" screenshot, I can see data owned by "testfacility", "testfacility, wettenhj" and "testfacility, steveand".  But in the "after" screenshot, it looks like all of the data is owned just by "testfacility".

![before](https://cloud.githubusercontent.com/assets/2209245/5848885/cceb8026-a231-11e4-8cd3-05968ffb1f67.PNG)

![after](https://cloud.githubusercontent.com/assets/2209245/5848912/27ce1b20-a232-11e4-8800-be3b49ae2585.PNG)

**Comment by wettenhj** [comment]
Solved by pulling in latest changes from https://github.com/jasonrig/mytardis/tree/facility_view_improvements

**Comment by wettenhj** [comment]
Reopening this issue because whilst it is now working for my MyTardis test server, the relevant changes from Jason's facility_view_improvements branch need to be merged into the MyTardis develop branch before this issue can be closed.

**Comment by jasonrig** [comment]
I think this can be closed now
