### ISSUE TITLE
SFTP doesn't show subdirectories within datasets

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#429]
This came up in testing ways to make Monash CryoEM data available to a collaborator in the UK.

**Comment by grischa** [comment]
Do you mean subdirectories defined by the directory fields on the dataset or datafile?

**Comment by grischa** [comment]
Looks like directories aren't implemented yet for SFTP.
Will add it soon

**Comment by wettenhj** [comment]
Just to clarify, MyData populates the directory field in the DataFile model, not the Dataset model.

**Comment by grischa** [comment]
fixed recently

**Comment by wettenhj** [comment]
Confirming that this fix works for me.  Thanks!
