### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by andrewjanke** [mytardis/mytardis#430]
The Help link in MyTardis 3.6 points to:

   https://github.com/mytardis/mytardis/wiki/UserGuide

This was last updated by "Tim Dettrick edited this page on 1 Dec 2011"

All of the screenshots are from v1.05 and show the Diffraction Image Repository interface which is now very much removed from the current interface.

**Comment by grischa** [comment]
Thanks @andrewjanke, I will update the link to point to current documentation

**Comment by grischa** [comment]
fixed by #759
