### ISSUE TITLE
Facility Overview progress seems to be broken

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#454]
To help with monitoring MyData uploads, I added some code to the Facility Overview to indicate how many bytes of a file had been uploaded so far: https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/views.py#L450

This seems to be broken now - the number of bytes uploaded displayed in the Facility Overview just remains at 0 until the file is verified.  I guess the code assumed that datafile.file_object.size would choose the datafile's temporary receiving storage box, but now maybe it is choosing the master storage box instead.  This issue is not worth spending a lot of time on, because as discussed elsewhere, some of the Facility Overview code needs to be rewritten to enable faster loading for large data collections, e.g. it might be easier to remove this code rather than fix it.

**Comment by wettenhj** [comment]
OK, here's the reason why the file size in facility overview isn't updating:
https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/datafile.py#L65

If a datafile has no verified DFOs, then datafile.file_object returns None, whereas the facility view code is expecting it to return the file_object for the partially uploaded datafile, so that we can check its size with datafile.file_object.size.

**Comment by wettenhj** [comment]
So instead of using datafile.file_object.size, we could use something like this:

```
dfo = DataFileObject.objects.get(datafile=datafile, storage_box=datafile.get_receiving_storage_box())
dfo.file_object.size
```

**Comment by grischa** [comment]
Good catch.
Maybe use `getattr(datafile.file_objects.first().file_object, 'size', 0)`?

**Comment by wettenhj** [comment]
It seems that this code isn't as robust as I thought it was:

```
                     file_object_size = \
-                        datafile.file_object.size \
-                        if datafile.file_object else 0
+                        getattr(datafile.file_objects.first().file_object,
+                                'size', 0)
```

I just got a 500 error while trying to load the Facility Overview:
```
Exception Value:	'NoneType' object has no attribute 'file_object'
```
