### ISSUE TITLE
HTML Descriptions in Experiment Index Pages

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#464]
Pages such as:

https://store.synchrotron.org.au/mydata/
https://store.synchrotron.org.au/public_data/

Don't render the HTML content of the experiment descriptions properly. This needs to be stripped out or rendered, I'd suggest.

**Comment by grischa** [comment]
Thanks for reporting. This is a configuration issue, not related to the code. I'll forward it to the relevant people.
