### ISSUE TITLE
Pre-emptive uploads via staging while checksumming for large files

### ISSUE THREAD

**Issue by keithschulze** [mytardis/mytardis#469]
I previously posted this [issue](https://github.com/monash-merc/mydata/issues/61#issuecomment-116876287) to the MyData repo but, as was point out, it's a limitation in the MyTardis API for staging via upload. 

MyData currently does MD5 checksum prior to commencing upload because the MyTardis API for upload via staging required the creation of a Datafile record, which in turn requires an MD5 checksum (if REQUIRE_DATAFILE_CHECKSUMS = True). For large files the MD5 checksum can take quite a lot of time (~20 min for 96GB file). Is there any way to enhance the API for upload via staging (at least for large files) to allow the commencement of pre-emptive chunk uploads in the background prior to having the MD5 checksum?

**Comment by wettenhj** [comment]
Without having thought much about the consequences of this, I think this could be achieved by moving the REQUIRE_DATAFILE_CHECKSUMS check from the Datafile model's "save" method to the "verify" method, but this would change the meaning of the REQUIRE_DATAFILE_CHECKSUMS setting, which might not be popular.

**Comment by grischa** [comment]
MyData can register the file by providing the path instead of requesting it. This would work best if each MyData installation creates a unique id and puts its files in a thus named folder.
So, file is created, MyData copies and checksums, once checksum is done, register file with MyTardis, while upload may or may not be done.
Thoughts @wettenhj ?

**Comment by grischa** [comment]
@wettenhj this would not be popular, you are correct.

**Comment by wettenhj** [comment]
@grischa, that sounds like a reasonable approach - I can't think of anything that would prevent it from working.  If we implement that, it would be good to update the MyTardis API documentation to explain the two different methods of uploading via staging.

**Comment by grischa** [comment]
Another option is to store a bogus checksum in mytardis and the file id in
mydata and update the record once the checksum is done

**Comment by wettenhj** [comment]
The bogus checksum approach sounds nice and simple - it requires no changes to MyTardis, except maybe an assurance that there are no immediate plans in MyTardis to add strict validation of checksums and reject them if they are obviously bogus.  So maybe this can be moved back to the MyData issues list?

A bit of work would still be required on the MyData side to achieve what @keithschulze is asking for - what is currently done in a single upload thread would need to fork into two separate threads (for MD5 summing and uploading), and then MyData would need to ensure that both threads have completed before calling the MyTardis API's verify endpoint.

**Comment by keithschulze** [comment]
I agree that bogus checksum seems like a simple solution. Can definitely understand that it will require quite a bit of work. Should we re-open MyData issue list and close it here?

**Comment by grischa** [comment]
The checksum can be of the standard length, just all zeros or whatever. If you set the size to be wrong as well, then it wouldn't even try to checksum the file and waste resources. Yes, move this to mydata
