### ISSUE TITLE
SHA512 sums not recorded in POST uploads. Effect on verifications and filters?

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#472]
For POST uploads missing SHA512 sums (e.g. triggered by the "Add files..." button in dataset view), MD5 sums are populated here:
https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/api.py#L940

SHA512 sums are also calculated, but they are not recorded in the bundle.data.  Presumably they should be?

This results in an additional call to DataFile's save method within the DataFileObject's verify method: 
https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/datafile.py#L605

This save shouldn't trigger the POST_SAVE filter if verified is False at the time, but I've seen evidence of the POST_SAVE datafile_hooks being triggered here in my logging.  I think it's due to another issue just raised about DFOs being saved multiple times in quick succession (by TastyPie), triggering multiple auto_verify_on_save calls around the same time, so in some of those dfo.verify() calls, the DataFileObject will already be verified when "df.save()" is called, triggering the POST_SAVE filter.

I'm currently testing just with interactive web-based uploads, but I'll also be testing this with MyData (which only populates the MD5 sum, not the SHA 512 sum, and uses staging uploads), so I'll be looking at whether populating the SHA 512 sum earlier or later in the save/verify pipeline leads to extra POST_SAVE triggers for MyData uploads.

**Comment by grischa** [comment]
I added a change for this to #474 

As mentioned in #471, filters should be written with the assumption that they are ran several times.
