### ISSUE TITLE
createsuperuser sometimes not listed in tardis_portal management commands

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#477]
This was actually reported to me by @keithschulze.  Not sure if I can reproduce it yet.

Keith installed the latest MyTardis on Mac OS X and ran the commands in build.sh for creating a new database which seemed to succeed except that "python mytardis.py syncdb --all" didn't accept the "--all" argument.

When Keith tried to create a superuser with "python mytardis.py createsuperuser", it appeared to work, but then we found that he had unintentionally run the Django "createsuperuser" command from the "auth" app, instead of the tardis_portal's "createsuperuser" command, so as a result, no UserProfile record was created, so an exception occurred when Keith tried to log in via the web interface.

tardis_portal's createsuperuser command seem to work OK on Keith's Mac when run from the Django shell.  From memory, we did something like this, and it was successful:
```
python mytardis.py shell_plus
>>> from tardis.tardis_portal.management.commands import createsuperuser
>>> cmd = createsuperuser.Command()
>>> cmd.handle(username='james123',password='test',email='test@example.com',interactive=False)
```
i.e. the above commands resulted in a UserProfile being created for user 'james123'.

But when we ran:
```python mytards.py```

there was no "createsuperuser" command in the "[tardis_portal]" section, only in the "[auth]" section.

**Comment by grischa** [comment]
Ah, that first thing is a bug in `build.sh`, Django 1.8 does not need `--all` anymore.
The `createsuperuser` command needs investigation
