### ISSUE TITLE
Access-Control-Allow-Origin header on API

### ISSUE THREAD

**Issue by jasonrig** [mytardis/mytardis#486]
API access from sites outside of the API's domain is disallowed due to there being no 'Access-Control-Allow-Origin' header. A public API should really allow any origin to access the resource.

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Origin

**Comment by grischa** [comment]
Should it really? I think that's debatable

**Comment by jasonrig** [comment]
Well it's not really a security feature anyway since a browser plugin can disable this check. But if the API is public, I would expect the headers to reflect this. On the other hand, if you don't characterise the API as public, then I suppose not.

**Comment by jasonrig** [comment]
Oops, I think I've misunderstood where this header is supposed to be. The API isn't sending it, but the server I'm using to test with.
