### ISSUE TITLE
Datafile previews should support a separate metadata store for each storage box.

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#490]
In tardis/tardis_portal/models/datafile.py: https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/datafile.py#L310

MyTardis looks here for preview images:

```
        if preview_image_par:
            file_path = path.abspath(path.join(settings.METADATA_STORE_PATH,
                                               preview_image_par.string_value))
```

It should be able to access preview images stored within the storage box of the preferred DataFileObject

**Comment by grischa** [comment]
We have talked about metadata stored in (hidden) datafiles, it's just not implemented yet.
The metadata would reference a file ID and the file could either be hidden or accessible and be part of the same experiment. Should be easier with the new data model though, so we held off until then.
