### ISSUE TITLE
loadschemas management command is broken

### ISSUE THREAD

**Issue by pansapiens** [mytardis/mytardis#493]
It appears that this code was overlooked in the upgrade to Django 1.8 - it uses several transaction methods that have been deprecated and no longer exist in Django.

**Comment by wettenhj** [comment]
The runfilters command also uses transaction methods which are not supported in Django 1.8

**Comment by pansapiens** [comment]
Note that a workaround is to use the `loaddata` command instead. Although it doesn't have all the features of the `loadschemas` command it's often good enough.

**Comment by wettenhj** [comment]
Addressed in 72586d780ab421df84021bb813a98b4c5411f199
