### ISSUE TITLE
"Some or all files in this dataset are archived" can be misleading for unverified datafiles

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#513]
If some files are not yet verified, e.g. because they are still being uploaded, MyTardis reports that "Some or all files in this dataset are archived" (which implies moved from disk to tape) when in fact it's possible that none of them are "archived", but some have not yet been verified.

**Comment by grischa** [comment]
Agreed, that's misleading. Will have a fix ready soon
