### ISSUE TITLE
Command 'createsuperuser' doesn't create a UserProfile

### ISSUE THREAD

**Issue by nrmay** [mytardis/mytardis#537]
# Problem
The 'auth' version is not being overridden by the 'mytardis' version, when running the following command:
    python mytardis.py createsuperuser
This means that no UserProfile is created for the user.

# Cause
Since Django 1.7 the priority of apps in the 'INSTALLED_APPS' setting appears to have changed.
Duplicate commands are ignored in subsequent apps.
To verify run the command:
    python mytardis.py
Check that the command 'createsuperuser' is displayed in the '[auth]' section.

# Solution
Move 'tardis.tardis_portal' to the top of the 'INSTALLED_APPS' list.

# Testing 
Run the command:
    python mytardis.py
Check that the command 'createsuperuser' is displayed in the 'tardis_portal' section.

**Comment by wettenhj** [comment]
Possible duplicate of https://github.com/mytardis/mytardis/issues/477

**Comment by nrmay** [comment]
Moving tardis_portal to the top of the installed apps causes many tests to fail.
Easier solution is to just rename the command to 'createmysuperuser', thus avoiding the override.
