### ISSUE TITLE
Slow page loading of view_dataset for large dataset

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#595]
I have a dataset with 88,000 files, and it takes 4.5 minutes to load the dataset view.

"dataset.is_online" is called twice in tardis/tardis_portal/templates/tardis_portal/view_dataset.html and seems to take a long time.

```
>>> timeit.timeit('from tardis.tardis_portal.models.dataset import Dataset; print str(Dataset.objects.get(id=24628).is_online)', number=1)
False
126.21493291854858
```

**Comment by grischa** [comment]
Initial thoughts are that a quick fix might be an ajax call to is_online for the dataset.
A proper fix would need to investigate whether we need this at all, and then whether we can optimise the SQL queries. The aggregate or group by queries might be useful, then the DB server can deliver the finished result.

**Comment by wettenhj** [comment]
Not sure whether this should be a separate issue, but ```dataset.get_images.count``` (used in the view_dataset.html template) is also too slow for very large datasets.  Can we limit the number of images in the Preview Images carousel to an arbitrary number?  ```dataset.get_images|slice:":10"|length``` is much faster than ```dataset.get_images.count```.
