### ISSUE TITLE
OperationalError at /stats/

### ISSUE THREAD

**Issue by sam-at-github** [mytardis/mytardis#636]
On new install I get an Exception trying to access the "Stats" tab: 

> OperationalError at /stats/
> 
> no such table: default_cache
> 
> Request Method:   GET
> Request URL:  http://nectar.epicmorsel.com:8000/stats/
> Django Version:   1.8.13
> Exception Type:   OperationalError
> Exception Value:  
> 
> no such table: default_cache
> 
> Exception Location:   /home/admin/.virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 318
> Python Executable:    /home/admin/.virtualenvs/mytardis/bin/python
> Python Version:   2.7.6
> Python Path:  
> 
> ['/home/admin/src/mytardis',
>  '/home/admin/.virtualenvs/mytardis/src/django-jasmine',
>  '/home/admin/.virtualenvs/mytardis/src/django-tastypie',
>  '/home/admin/.virtualenvs/mytardis/src/paramiko',
>  '/home/admin/.virtualenvs/mytardis/src/python-magic',
>  '/home/admin/.virtualenvs/mytardis/lib/python2.7',
>  '/home/admin/.virtualenvs/mytardis/lib/python2.7/plat-x86_64-linux-gnu',
>  '/home/admin/.virtualenvs/mytardis/lib/python2.7/lib-tk',
>  '/home/admin/.virtualenvs/mytardis/lib/python2.7/lib-old',
>  '/home/admin/.virtualenvs/mytardis/lib/python2.7/lib-dynload',
>  '/usr/lib/python2.7',
>  '/usr/lib/python2.7/plat-x86_64-linux-gnu',
>  '/usr/lib/python2.7/lib-tk',
>  '/home/admin/.virtualenvs/mytardis/local/lib/python2.7/site-packages',
>  '/usr/local/lib/python2.7/dist-packages/h5json-1.0.2-py2.7.egg',
>  '/home/admin/src/mytardis/src/django-jasmine',
>  '/home/admin/src/mytardis/src/django-tastypie',
>  '/home/admin/src/mytardis/src/paramiko',
>  '/home/admin/src/mytardis/src/python-magic',
>  '/usr/local/lib/python2.7/site-packages',
>  '/usr/local/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages']
> 
> Server time:  Mon, 30 May 2016 15:16:41 +1000

**Comment by grischa** [comment]
Is this missing from the docs?
https://github.com/mytardis/mytardis/blob/develop/build.sh#L39

**Comment by sam-at-github** [comment]
Yeah it's missing from the guide I was following - https://mytardis.readthedocs.io/en/develop/admin/install.html
