### ISSUE TITLE
Verification issue when trying to download multiple files or TAR

### ISSUE THREAD

**Issue by ibrahimtaoube** [mytardis/mytardis#680]
Hi,

We are trying to download mulitple files at the same time using TAR option or the "Download Selected Files" option on the experiment page. However whenever we attempt to use this feature we get the following message "The experiment you are trying to access has not yet been verified completely. Verification is an automated background process. Please try again later or contact the system administrator if the issue persists." Furthermore if we download the files individually via the corresponding download icon the file downloads fine but if we use the Download Select Files button on that single file then we see that same error. These files were uploaded via SSH  a few days ago.

The mytardis.log shows the following.
`[04/Nov/2016 16:03:21] ERROR   download streaming_download_datafiles In download_datafiles !!
[04/Nov/2016 16:03:21] INFO    download streaming_download_datafiles Files for archive command: set([<DataFile: 914788124c51c3137bc7cfa4f62bef2d R04_19992.RHIT # application/octet-stream>])
[04/Nov/2016 16:03:44] ERROR   download streaming_download_datafiles In download_datafiles !!
[04/Nov/2016 16:03:44] INFO    download streaming_download_datafiles Files for archive command: set([<DataFile: d09482b7defa22dfc7eda87a4b29ecbe R04_19957.RHIT # application/octet-stream>])
[04/Nov/2016 16:06:25] ERROR   download streaming_download_datafiles In download_datafiles !!
[04/Nov/2016 16:06:25] INFO    download streaming_download_datafiles Files for archive command: set([<DataFile: d09482b7defa22dfc7eda87a4b29ecbe R04_19957.RHIT # application/octet-stream>, <DataFile: 783284ff4c500d61bb5f2036e14b9679 R04_19990.RHIT # application/octet-stream>])`

Furthermore the admin interface clearly shows the files have already been verified as shown below. So what might have caused this issue? Thank you
![screen shot 2016-11-04 at 4 19 57 pm](https://cloud.githubusercontent.com/assets/1930151/19995362/a910e350-a2aa-11e6-8d58-7e80d4c4cd6d.png)

**Comment by wettenhj** [comment]
Hi Ibi,

Can you run the Django shell (python mytardis.py shell_plus), and check the modification time for one or more of these DataFile records?

e.g.

df = DataFile.objects.get(filename="R04_19992.RHIT")
df.modification_time

There was an issue with MyData not populating the modification_time field when it created DataFile records which may be affecting you.

**Comment by ibrahimtaoube** [comment]
I had a look at the file "R04_19992.RHIT copy”. In the administration portal it says the modification time is “2016-11-01 09:50:59”. I loaded up the Django shell and checked the modification time of that file and it is “datetime.datetime(2016, 10, 31, 22, 50, 59, tzinfo=<UTC>)”.

`cd /home/devel/mytardis
../Python-2.7.6/python mytardis.py shell_plus
Python 2.7.6 (default, Mar 15 2016, 16:24:33) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> df = DataFile.objects.get(filename="R04_19992.RHIT copy")
>>> df.modification_time
datetime.datetime(2016, 10, 31, 22, 50, 59, tzinfo=<UTC>)`


![screen shot 2016-11-07 at 10 01 02 am](https://cloud.githubusercontent.com/assets/1930151/20042596/1f7253e4-a4d1-11e6-98ab-95adf4baa752.png)

**Comment by wettenhj** [comment]
Thanks Ibi,

So it doesn't look like the "known issue" I was referring to with missing modification times in uploads from older MyData versions.  What version of MyTardis are you using?

**Comment by ibrahimtaoube** [comment]
No problem.

This server is running version 3.7.1 of MyTardis, 
released Thu, 7 Apr 2016 11:06:35 +1000

**Comment by wettenhj** [comment]
This fix could help you: https://github.com/mytardis/mytardis/commit/6511f9f6db51a6922437222955a658c7d5189559

If not, @grischa might have other suggestions.

**Comment by grischa** [comment]
There have been a few bug-fixes on the download functions since 3.7.1, so I recommend upgrading (https://github.com/mytardis/mytardis/compare/3.7.1...3.7#diff-bd66329b35549d29a90a0a46fa24e462)

If you still have trouble, you could turn on emails for server errors, then you get a traceback by email.
For this you need to set up the email server in the settings and provide an Admin contact there, too.

**Comment by ibrahimtaoube** [comment]
Updating to the latest version of MyTardis has resolved the issue.

Thank you
