### ISSUE TITLE
Instrument schema does not 'stick'

### ISSUE THREAD

**Issue by RichardPBerry** [mytardis/mytardis#779]
When assigning an Instrument to a dataset through the MyTardis UI it does not stay assigned. To replicate:

1. Select a dataset
2. Choose edit data set
3. Set a value for the Instrument parameter. ![instrument parameter setting](https://cloud.githubusercontent.com/assets/22140635/21168959/1bf2a20c-c20c-11e6-8f00-ba710c049d06.png)
4. Click save.
5. Reopen the dataset metadata (edit window). The "Instrument" parameter is not updated.

An instrument cat be set through the Admin interface or when uploaded via the MyData client.

**Comment by wettenhj** [comment]
Thanks for reporting this bug.

The edit_dataset method seems to only save the "Description" field, not the others:

https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/views/pages.py#L855

**Comment by RichardPBerry** [comment]
That would explain it :)  I played around with the directory field but I'm not really sure what this field is supposed to do?
