### ISSUE TITLE
Publication forms hangs at [PUBLICATION] Awaiting Release

### ISSUE THREAD

**Issue by RichardPBerry** [mytardis/mytardis#790]
Using the Publication Forms method for publishing an experiment seems to hang after the 'Approve' stage, even if no embargo period is applied. After selecting Approve from the review panel the publication status is set to "[PUBLICATION] Awaiting Release" and seems to stay there (screenshot attached). The resulting experiment is not publicly accessible.

![screen shot 2017-01-10 at 4 56 54 pm](https://cloud.githubusercontent.com/assets/22140635/21795556/bdad3d50-d756-11e6-9cdf-3df2513fcd6d.png)

**Comment by jasonrig** [comment]
Publication release, whether an embargo period is applied or not (actually, one always is set but it's often the set to the current time), relies upon a background celery task executing. Double-check that the tasked named "apps.publication_forms.update_publication_records" is in the celerybeat schedule in the settings, [as described here](http://mytardis.readthedocs.io/en/develop/apps/publication_forms.html#basic-setup), with a reasonably short interval. If that fails, check the celery logs to see if something else is causing the release to fail.

**Comment by hutho6** [comment]
Thanks @jasonrig, publications are now working.

**Comment by jasonrig** [comment]
Great! Happy to help :)
