### ISSUE TITLE
DuplicateKey error in API should not raise an InternalServerError

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#832]
We've had a request to allow MyData to be run from multiple user accounts with a shared config: https://github.com/mytardis/mydata/issues/105

This leads to an increased risk of multiple MyData sessions running concurrently, pointing to the same shared data directory (e.g. D:\Data), potentially resulting in Duplicate Key errors from the MyTardis API.

This can lead to thousands of InternalServerError emails being sent to MyTardis admins.  We should change the MyTardis API, so that it returns an HTTP code indicating a client error (e.g. 409), instead of raising an InternalServerError.

**Comment by wettenhj** [comment]
Fixed for DataFileResource here: https://github.com/mytardis/mytardis/pull/841
and here: https://github.com/mytardis/mytardis-app-mydata/pull/9

The same thing should probably be done for other API resources, but the intention of this issue was to focus on the DataFileResource case, so I think we can close this issue.

**Comment by grischa** [comment]
Can you close this issue, @wettenhj ?
