### ISSUE TITLE
centos 7 installation error.

### ISSUE THREAD

**Issue by kyaky** [mytardis/mytardis#853]
Hi Community,

I'm new to myTardis. When I follow 3.7 installation guide I get this error on CentOS7. Please advise. Thanks

` Running setup.py develop for paramiko
  Running setup.py install for olefile ... done
  Running setup.py install for pwgen ... done
  Running setup.py install for configparser ... done
  Running setup.py install for wrapt ... done
  Running setup.py install for pyoai ... done
  Running setup.py install for pysolr ... done
  Running setup.py develop for python-magic
  Running setup.py install for rdfextras ... done
  Running setup.py install for pyyaml ... done
  Running setup.py install for ua-parser ... done
  Running setup.py install for user-agents ... done
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools-0.9.8:
      Successfully uninstalled setuptools-0.9.8
  Running setup.py install for python-ldap ... error
    Complete output from command /root/.virtualenvs/mytardis/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-PcrzFD/python-ldap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1BheTx-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/mytardis/include/site/python2.7/python-ldap:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/.virtualenvs/mytardis/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/root/.virtualenvs/mytardis/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/root/.virtualenvs/mytardis/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/root/.virtualenvs/mytardis/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
        MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
    TypeError: __call__() takes exactly 2 arguments (1 given)

    ----------------------------------------
Command "/root/.virtualenvs/mytardis/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-PcrzFD/python-ldap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1BheTx-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/mytardis/include/site/python2.7/python-ldap" failed with error code 1 in /tmp/pip-build-PcrzFD/python-ldap/
(mytardis)[root@localhost mytardis]#
`

**Comment by wettenhj** [comment]
We usually install MyTardis on Ubuntu 14.04 LTS.  You might encounter a few more obstacles installing on CentOS 7 instead of Ubuntu.  Also, using the "root" account to install Python modules in your MyTardis virtualenv is **_not recommended_** - the whole point of using a virtualenv is so that you can safely install Python module dependencies as a non-root user and avoid risking messing up the system-wide Python installation.

See: https://bugs.centos.org/view.php?id=12722&history=1

Some relevant information from the linked bug report:

- "Upgrading to pyparsing 2.1.10 (latest version) is the recommended course of action"

One response from that bug reports says:
- "You've almost certainly broken your system by running pip as root."

**Comment by kyaky** [comment]
thank you, wettenhj.

I will make sure I have more reading of the documentation first...

Cheers
