### ISSUE TITLE
List most recent datasets at the top of the experiment view, on the first page

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#986]
https://github.com/mytardis/mytardis/pull/985

**Comment by eresearchrmit** [comment]
I'm happy for the default behaviour to be "most recent first", but it would be good if there were some sort of switch to enable the original behaviour (i.e., in the settings file).

**Comment by wettenhj** [comment]
Thanks for the feedback.  Assuming "eresearchrmit" is Nick or Ian?

Yes, we can make this configurable in settings.py - I'll add that to the Pull Request.

**Comment by wettenhj** [comment]
This was done in a configurable way with the default behaviour being backwards compatible, so it didn't need to wait until 4.0.

It has been merged in this PR: https://github.com/mytardis/mytardis/pull/985
